version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: wordpress_mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:6.2.0-php8.2-fpm
    container_name: wordpress_wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - wordpress

  nginx:
    image: nginx:stable
    container_name: wordpress_nginx
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - mysql
      - wordpress
    networks:
      - wordpress

volumes:
  mysqldb:
networks:
  wordpress:
    driver: bridge